theme: jekyll-theme-minimal
title: Evolution of gender roles in film accros the decades Website
description: Analysis of gender respresentation and gener stereotypes utilising time, movie genres, film trops and actors.
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
